# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michal Malik's blog
email: michal.malik@devrandom.sk
description: > # this means to ignore newlines until "baseurl:"
 Technical blog about reverse engineering Linux.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michalmalik.github.io" # the base hostname & protocol for your site

github_username: michalmalik
google_analytic_id:
disqus_name:

permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num

# jekyll seo tag settings
twitter:
  username: michalmalik

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
